config/routes.rb
Rails.application.routes.draw do

  resources :products
  resources :line_items
  resources :carts
  resources :mon_comptes
  resources :items
  resources :locations_achats
  namespace :locations do
  resources :achats
  end
  resources :contacts, only: [:new, :create] do
      get "/thanks" => "contacts#thanks"
    end

  devise_for :users
  root to: 'pages#home'
  get '/qui_sommes_nous', to: 'pages#qui_sommes_nous'
  get '/acheter_une_voiture', to: 'pages#acheter_une_voiture'
  get '/louer_une_voiture', to: 'pages#louer_une_voiture'
  get '/ferrari', to: 'pages#ferrari'
  get '/lamborghini', to: 'pages#lamborghini'
  get '/mon_compte', to: 'pages#mon_compte'
  get '/catalog', to: 'catalog#catalog'
  get '/message', to: 'pages#message'

  #Delete

  delete '/message', to: 'pages#message'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product)
  item = line_items.find_by(product: product)

  if item
    item.quantity += 1
  else
    item = line_items.new(product: product)
  end

  item
end

def total
  line_items.to_a.sum(&:total)
end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :cart_not_found
  before_action :set_cart, only: %i[ show edit update destroy ]

  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1 or /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy

@cart.destroy
session.delete(:cart_id)

respond_to do |format|
  format.html { redirect_to carts_path, notice: "Votre panier est vide"}
      format.json { head :no_content }
    end
  end

  private

  def cart_not_found
  redirect_to root_url, alert: t(".cart_not_found")
end

    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/views/carts/_form.html.erb
<%= simple_form_for(@cart) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/34577/pexels-photo.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260);">
  <div class="container">
    <p></p>
  </div>
</div>

<h1>Modifier votre panier</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<style>
      .banner-image {
        background-image: url('https://images.pexels.com/photos/34577/pexels-photo.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260');
        background-size: cover;
      }
    </style>

<div class="container">
  <div class="row">
    <div class="col-sm">

      <p id="notice"><%= notice %></p>

      <h1 style="text-align:center">Mon Panier</h1>

      <table>
        <thead>
          <tr>
            <th colspan="3"></th>
          </tr>
        </thead>

        <% @carts.each do |cart| %>
        <tr>
          <div style="text-decoration:none;" class="text-center">
            <p><%= link_to 'Voir votre panier', cart %></p>
            <p><%= link_to 'Modifier votre panier', edit_cart_path(cart) %></p>
            <p><%= link_to 'Supprimer votre panier', cart, method: :delete, data: { confirm: 'Are you sure?' } %></p>
          </tr>
          <% end %>
        </table>

        <br>

        <div class="text-center">
          <%= link_to 'New Cart', new_cart_path %>
        </div>

        <br>

      </div>
    </div>
  </div>

app/views/carts/new.html.erb
<style>
      .banner-image {
        background-image: url('https://images.pexels.com/photos/34577/pexels-photo.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260');
        background-size: cover;
      }
    </style>

  <div class="container">
    <div class="row">
      <div class="col-xs-2">
        <div class="text-center">

        <br>

        <h1>Nouveau Panier</h1>

        <%= render 'form', cart: @cart %>

        <%= link_to 'Retour Acceuil', root_path %>

      </div>
    </div>
  </div>
</div>

app/views/carts/show.html.erb
<style>
      .banner-image {
        background-image: url('https://images.pexels.com/photos/34577/pexels-photo.jpg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260');
        background-size: cover;
      }
    </style>

<div class="container">
  <div class="row">
    <div class="col-xs mx-auto">
      <br>

      <h2 class="titrepanier">Mon panier</h2>

      <br>

        <% @cart.line_items.each do |item| %>
        <%= item.product.title %> (x <%= item.quantity %>) <span class="badge badge-info"><%= number_to_currency(item.total, unit: "€", separator: ",", format: "%n %u") %></span>
          <% end %>


        <p class="font-weight-bold">Total : <span class="badge badge-info"><%= number_to_currency(@cart.total, unit: "€", separator: ",", format: "%n %u") %></span></p>



          <p><span class="text-align"><%= link_to "Retour aux produits", acheter_une_voiture_path, class: "btn btn-primary" %></span></p>

         <p><%= button_to "Vider le panier", @cart, method: :delete, data: {
            confirm: "Êtes-vous sûr ?" }, class: "btn btn-danger" %></p>

          </div>
        </div>

</div>
<br>
</div>