config/routes.rb
Rails.application.routes.draw do

  resources :products
  resources :line_items
  resources :carts
  resources :mon_comptes
  resources :items
  resources :locations_achats
  namespace :locations do
  resources :achats
  end
  resources :contacts, only: [:new, :create] do
      get "/thanks" => "contacts#thanks"
    end

  devise_for :users
  root to: 'pages#home'
  get '/qui_sommes_nous', to: 'pages#qui_sommes_nous'
  get '/acheter_une_voiture', to: 'pages#acheter_une_voiture'
  get '/louer_une_voiture', to: 'pages#louer_une_voiture'
  get '/ferrari', to: 'pages#ferrari'
  get '/lamborghini', to: 'pages#lamborghini'
  get '/mon_compte', to: 'pages#mon_compte'
  get '/catalog', to: 'catalog#catalog'
  get '/message', to: 'pages#message'

  #Delete

  delete '/message', to: 'pages#message'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/locations_achat.rb
class LocationsAchat < ApplicationRecord
  mount_uploader :photo, PhotoUploader

end

app/controllers/locations_achats_controller.rb
class LocationsAchatsController < ApplicationController
  before_action :set_locations_achat, only: %i[ show edit update destroy ]

  # GET /locations_achats or /locations_achats.json
  def index
    @locations_achats = LocationsAchat.all
  end


  # GET /locations_achats/1 or /locations_achats/1.json
  def show
    @locations_achats = LocationsAchat.all
  end

  # GET /locations_achats/new
  def new
    @locations_achat = LocationsAchat.new
  end

  # GET /locations_achats/1/edit
  def edit
  end

  # POST /locations_achats or /locations_achats.json
  def create
    @locations_achat = LocationsAchat.new(locations_achat_params)

    respond_to do |format|
      if @locations_achat.save
        format.html { redirect_to @locations_achat, notice: "Locations achat was successfully created." }
        format.json { render :show, status: :created, location: @locations_achat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @locations_achat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations_achats/1 or /locations_achats/1.json
  def update
    respond_to do |format|
      if @locations_achat.update(locations_achat_params)
        format.html { redirect_to @locations_achat, notice: "Locations achat was successfully updated." }
        format.json { render :show, status: :ok, location: @locations_achat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @locations_achat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations_achats/1 or /locations_achats/1.json
  def destroy
    @locations_achat.destroy
    respond_to do |format|
      format.html { redirect_to locations_achats_url, notice: "Locations achat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_locations_achat
      @locations_achat = LocationsAchat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def locations_achat_params
      params.require(:locations_achat).permit(:achat_location, :nom_voiture, :vitesse_max, :acceleration, :puissance, :prix, :photo)
    end
end

app/views/locations_achats/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm text-center">

      <br><br>

<%= simple_form_for(@locations_achat) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">

    <%= f.label :achat_location, class:"btn active" do %>
    <%= f.radio_button :achat_location, true %>
    Voiture pour Achat
    <% end %>

    <%= f.label :achat_location, class:"btn active" do %>
    <%= f.radio_button :achat_location, false, checked: true %>
    Voiture pour l'Ocassion
    <% end %>

    <%= f.input :nom_voiture %>
    <%= f.input :vitesse_max %>
    <%= f.input :acceleration %>
    <%= f.input :puissance %>
    <%= f.input :prix %>
    <%= f.input :photo, label: "Une photo de la voiture", hint: "La photo est obligatoire et doit être au format jpeg, png, gif ou bmp :)"%>

  </div>

  <div class="form-actions">
    <%= f.button :submit, "Ajouter/Éditer fiche nouvelle voiture" %>
  </div>
<% end %>

</div>
</div>
</div>

app/views/locations_achats/edit.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/1148820/pexels-photo-1148820.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260);">
  <div class="container">
    <h1>Gestion des voitures Locations/Achats</h1>
    </div>
  </div>

  <br>

<h1 class="text-center">Édition fiche voiture</h1>

<%= render 'form', locations_achat: @locations_achat %>

<div class="text-center">
<%= link_to 'Voir la fiche', @locations_achat %> |
<%= link_to 'Retour vers index', locations_achats_path %>
</div>

app/views/locations_achats/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/1148820/pexels-photo-1148820.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260);">
  <div class="container">
    <h1>Gestion des voitures Locations/Achats</h1>
     <div class='btn btn-flat'>
        <%= link_to new_locations_achat_path do %>
        +🏎
        <% end %>
      </div>

  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm">
      <br>
       <ul class="grid2">

          <% @locations_achats.each do |locations_achat| %>

            <div class="card" style="width: 18rem;">
              <%= cl_image_tag locations_achat.photo, :width => 282, :crop => "pad" %>
              <div class="card-body">

                <p><strong>Modèle voiture: </strong><%= locations_achat.nom_voiture %></p>

                <p><strong>Vitesse Maximum: </strong><%= locations_achat.vitesse_max %></p>

                <p><strong>Acceleration: </strong><%= locations_achat.acceleration %></p>

                <p><strong>Puissance du véhicule: </strong><%= locations_achat.puissance %></p>

                <p><strong>Prix du véhicule: </strong><%= locations_achat.prix %></p>
              </div>
              <hr style="background: orange;">
              <div class="notification-actions text-center">
                <%= link_to edit_locations_achat_path(locations_achat) do %>
                Editer <i class="fas fa-pencil-alt"></i>
                <% end %>
                <%= link_to locations_achat_path(locations_achat), method: :delete, data: {confirm: 'Êtes vous sûrs de vouloir supprimer ?' } do %>
                Supprimer <i class="far fa-trash-alt"></i>
                <% end %>
              </div>
          </div>
          <% end %>
        </ul>
    </div>
  </div>
</div>

app/views/locations_achats/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/1148820/pexels-photo-1148820.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260);">
  <div class="container">
    <h1>Gestion des voitures Locations/Achats</h1>
    </div>
  </div>

  <br>

<h1 class="text-center">Nouvelle voiture à mettre dans la base de données</h1>

<%= render 'form', locations_achat: @locations_achat %>

<div class="text-center">
<%= link_to 'Retour Index', locations_achats_path %>
</div>

app/views/locations_achats/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/1148820/pexels-photo-1148820.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260);">
  <div class="container">
    <h1>Gestion des voitures Locations/Achats</h1>
    </div>
  </div>

<div class="container">
  <div class="row">
    <div class="col-sm">

      <p id="notice"><%= notice %></p>

      <div class="card-body text-center">

        <p>
          <strong>Nom voiture:</strong>
          <%= @locations_achat.nom_voiture %>
        </p>

        <p>
          <strong>Vitesse max:</strong>
          <%= @locations_achat.vitesse_max %>
        </p>

        <p>
          <strong>Acceleration:</strong>
          <%= @locations_achat.acceleration %>
        </p>

        <p>
          <strong>Puissance:</strong>
          <%= @locations_achat.puissance %>
        </p>

        <p>
          <strong>Prix:</strong>
          <%= @locations_achat.prix %>
        </p>

        <p>
          <%= cl_image_tag @locations_achat.photo, :width => 285, :crop => "pad" %>
        </p>

        <%= link_to 'Editer', edit_locations_achat_path(@locations_achat) %> |
        <%= link_to 'Retour Index', locations_achats_path %>
      </div>
    </div>
  </div>
</div>
</div>